stages:
  - compile
  - test
  - deploy

build:
  stage: compile
  image: golang:latest
  script:
    - go get -d -v
    - go build -o bin/gg-cms -v .

test:
  stage: test
  image: golang:latest
  script:
    - go test
    - go test ./...

deploy:
  stage: deploy
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gg-cms --api-key=$HEROKU_API_KEY
  environment:
    name: Development
    url: https://gg-cms.herokuapp.com/
  only:
    - GitLab